-- Generated by scripts/fetch-company-logos.mts
-- 2026-07-20T20:00:47.231Z

UPDATE companies SET logo_url = 'https://mzxvtugnniskdmpmmjpj.supabase.co/storage/v1/object/public/company-logos/co-aep.webp' WHERE id = 'co-aep';
UPDATE companies SET logo_url = 'https://mzxvtugnniskdmpmmjpj.supabase.co/storage/v1/object/public/company-logos/co-ap.webp' WHERE id = 'co-ap';
UPDATE companies SET logo_url = 'https://mzxvtugnniskdmpmmjpj.supabase.co/storage/v1/object/public/company-logos/co-atp.webp' WHERE id = 'co-atp';
UPDATE companies SET logo_url = 'https://mzxvtugnniskdmpmmjpj.supabase.co/storage/v1/object/public/company-logos/co-btp.webp' WHERE id = 'co-btp';
UPDATE companies SET logo_url = 'https://mzxvtugnniskdmpmmjpj.supabase.co/storage/v1/object/public/company-logos/co-ctp.webp' WHERE id = 'co-ctp';
UPDATE companies SET logo_url = 'https://mzxvtugnniskdmpmmjpj.supabase.co/storage/v1/object/public/company-logos/co-dtp.webp' WHERE id = 'co-dtp';
UPDATE companies SET logo_url = 'https://mzxvtugnniskdmpmmjpj.supabase.co/storage/v1/object/public/company-logos/co-ipp.webp' WHERE id = 'co-ipp';
UPDATE companies SET logo_url = 'https://mzxvtugnniskdmpmmjpj.supabase.co/storage/v1/object/public/company-logos/co-kvp.webp' WHERE id = 'co-kvp';
UPDATE companies SET logo_url = 'https://mzxvtugnniskdmpmmjpj.supabase.co/storage/v1/object/public/company-logos/co-matp.webp' WHERE id = 'co-matp';
UPDATE companies SET logo_url = 'https://mzxvtugnniskdmpmmjpj.supabase.co/storage/v1/object/public/company-logos/co-mr.webp' WHERE id = 'co-mr';
UPDATE companies SET logo_url = 'https://mzxvtugnniskdmpmmjpj.supabase.co/storage/v1/object/public/company-logos/co-nep.webp' WHERE id = 'co-nep';
UPDATE companies SET logo_url = 'https://mzxvtugnniskdmpmmjpj.supabase.co/storage/v1/object/public/company-logos/co-obp.webp' WHERE id = 'co-obp';
UPDATE companies SET logo_url = 'https://mzxvtugnniskdmpmmjpj.supabase.co/storage/v1/object/public/company-logos/co-oftp.webp' WHERE id = 'co-oftp';
UPDATE companies SET logo_url = 'https://mzxvtugnniskdmpmmjpj.supabase.co/storage/v1/object/public/company-logos/co-sgp.webp' WHERE id = 'co-sgp';
UPDATE companies SET logo_url = 'https://mzxvtugnniskdmpmmjpj.supabase.co/storage/v1/object/public/company-logos/co-smtp.webp' WHERE id = 'co-smtp';
UPDATE companies SET logo_url = 'https://mzxvtugnniskdmpmmjpj.supabase.co/storage/v1/object/public/company-logos/co-snp.webp' WHERE id = 'co-snp';
UPDATE companies SET logo_url = 'https://mzxvtugnniskdmpmmjpj.supabase.co/storage/v1/object/public/company-logos/co-stp.webp' WHERE id = 'co-stp';
